### ISSUE TITLE
Mysql access denied for v1.3.0 on Capistrano assets:precompile

### ISSUE THREAD

**Issue by wbotelhos** [RubyMoney/money-rails#282]
Hi,

Just for information, when I updated to version 1.3.0 the method `init` from `hooks.rb` try to connect on my database during Capistrano `deploy:assets:precompile`, and it raises access denied error. I locked it on version `1.2.0` and now its fine.

```ruby
INFO [24452e15] Running bundle exec rake assets:precompile as deploy@app.com
(Backtrace restricted to imported tasks)
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@app.com: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES)
/var/www/app/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect'
/var/www/app/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `initialize'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:436:in `new_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:565:in `retrieve_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/hooks.rb:18:in `block in init'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/var/www/app/shared/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/hooks.rb:5:in `init'
/var/www/app/shared/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/railtie.rb:4:in `block in <class:Railtie>'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
/var/www/app/releases/20150201153616/config/environment.rb:3:in `<top (required)>'
/var/www/app/shared/bundle/ruby/2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
/var/www/app/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)

SSHKit::Command::Failed: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES)
/var/www/app/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect'
/var/www/app/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `initialize'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:436:in `new_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:565:in `retrieve_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/hooks.rb:18:in `block in init'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/var/www/app/shared/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/hooks.rb:5:in `init'
/var/www/app/shared/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/railtie.rb:4:in `block in <class:Railtie>'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
/var/www/app/releases/20150201153616/config/environment.rb:3:in `<top (required)>'
/var/www/app/shared/bundle/ruby/2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
/var/www/app/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)

Tasks: TOP => deploy:assets:precompile
(See full trace by running task with --trace)
The deploy has failed with an error: Exception while executing as deploy@app.com: rake exit status: 1
rake stdout: Nothing written
rake stderr: rake aborted!
Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES)
/var/www/app/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect'
/var/www/app/shared/bundle/ruby/2.2.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `initialize'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:436:in `new_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:565:in `retrieve_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
/var/www/app/shared/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/hooks.rb:18:in `block in init'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
/var/www/app/shared/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/hooks.rb:5:in `init'
/var/www/app/shared/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/railtie.rb:4:in `block in <class:Railtie>'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `public_send'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/railtie.rb:194:in `method_missing'
/var/www/app/releases/20150201153616/config/environment.rb:3:in `<top (required)>'
/var/www/app/shared/bundle/ruby/2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/skylight-0.6.0/lib/skylight/probes.rb:81:in `require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
/var/www/app/shared/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
/var/www/app/shared/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
/var/www/app/shared/bundle/ruby/2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
Tasks: TOP => environment
(See full trace by running task with --trace)
```

Thanks for the great gem. (:

**Comment by semmons99** [comment]
Can you run this locally without Capistrano? Looks to me like Cap isn't finding your DB creds or the creds aren't correct.

**Comment by grossadamm** [comment]
I ran into the same issue. 

We precompile our assets locally on a build agent so that our multiple production servers do not need to precompile the assets. The build agent does not have access to the production database. 

When running `rake assets:precompile` with money_rails 1.3.0, the application attempts to connect to the database which fails causing the pre-compilation to fail.

Downgrading to money_rails 1.2.0 solved this issue.

Stacktrace after running `rake assets:precompile RAILS_ENV=production`

    rake aborted!
    Mysql2::Error: Can't connect to local MySQL server through socket '/tmp/mysql.sock' (2)
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `connect'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/mysql2-0.3.17/lib/mysql2/client.rb:70:in `initialize'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `new'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/mysql2_adapter.rb:18:in `mysql2_connection'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:436:in `new_connection'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:565:in `retrieve_connection'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/hooks.rb:18:in `block in init'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/hooks.rb:5:in `init'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/money-rails-1.3.0/lib/money-rails/railtie.rb:4:in `block in <class:Railtie>'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
    /Users/adamgross/dev/application/src/config/environment.rb:5:in `<top (required)>'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
    /Users/adamgross/dev/application/src/vendor/bundle/ruby/2.2.0/gems/sprockets-rails-2.2.4/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'

**Comment by semmons99** [comment]
It would be of great help if you can figure out what changed made this occur so we can fix it (or you can fix it).

**Comment by grossadamm** [comment]
My plan is to delve into the money-rails code more in depth when I have a chance. I got as far as looking at the hooks.rb file and had to move on. But I figured I would give another example in case someone else runs into this as well.

**Comment by grossadamm** [comment]
Had a few more minutes. Looks like line 18 on `hooks.rb` asks for the instance of the ActiveRecord connection. This will attempt to create a connection if one does not exist. So since these hooks are activated when rake tasks run, an instance of the the connection is attempted to be created. It then fails and bombs out.

Not sure how to resolve yet.

**Comment by semmons99** [comment]
we should be able to check if the connection is active right before that and bail if it's not

**Comment by semmons99** [comment]
Closed due to inactivity.
