### ISSUE TITLE
Cannot bootstrap rails project with rake db:create

### ISSUE THREAD

**Issue by timcheadle** [RubyMoney/money-rails#288]
I'm starting on a new project and I can't create the databases for the first time if the `money-rails` gem is installed.

```
$ rake db:create:all
/Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect': FATAL:  database "appname_development" does not exist
 (ActiveRecord::NoDatabaseError)
```

As `rake` starts the entire Rails environment before executing the `db:create` task, the gem's initialization code is triggered. I did some digging and it looks like this line is to blame:

https://github.com/RubyMoney/money-rails/blob/v1.3.0/lib/money-rails/hooks.rb#L18

It is trying to retrieve an ActiveRecord connection for a database that doesn't exist. Well of course it doesn't exist, I'm trying to create it. =)

I fixed this by commenting out the `money-rails` gem from the Gemfile, running db:create, then uncommenting the gem. Weirdly, I can now do `db:drop db:create` and it still works fine.

Gemfile:
```
source 'https://rubygems.org'


gem 'rails', '4.2.0'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'haml', '>= 4.0.0'
gem 'haml-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', platforms: :ruby

gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'
#
# Currencies
gem 'money-rails', '~> 1.3.0'

# User authentication
gem 'devise'
gem 'cancancan', '~> 1.10'

# Data entry and viewing made easy
gem 'activeadmin', github: 'activeadmin'

# Use Unicorn as the app server
gem 'unicorn'



# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  gem 'pry'
  gem 'rspec-rails'

  gem 'byebug'

  gem 'web-console', '~> 2.0'

  gem 'spring'
end
```

Stack trace:
```
$ rake db:create:all
/Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `rescue in connect': FATAL:  database "appname_development" does not exist
 (ActiveRecord::NoDatabaseError)
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:651:in `connect'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:242:in `initialize'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `new'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/postgresql_adapter.rb:44:in `postgresql_connection'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:436:in `new_connection'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:446:in `checkout_new_connection'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:422:in `acquire_connection'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:349:in `block in checkout'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:348:in `checkout'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:263:in `block in connection'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/monitor.rb:211:in `mon_synchronize'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:262:in `connection'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_adapters/abstract/connection_pool.rb:565:in `retrieve_connection'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:113:in `retrieve_connection'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:87:in `connection'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/money-rails-1.3.0/lib/money-rails/hooks.rb:18:in `block in init'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/money-rails-1.3.0/lib/money-rails/hooks.rb:5:in `init'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/money-rails-1.3.0/lib/money-rails/railtie.rb:4:in `block in <class:Railtie>'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `call'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:224:in `tsort_each'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/tsort.rb:205:in `tsort_each'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
	from /Users/tim/Dropbox/src/appname/config/environment.rb:5:in `<top (required)>'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:92:in `preload'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:143:in `serve'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/tim/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'

**Comment by pftg** [comment]
Fixed by #287

**Comment by pftg** [comment]
@timcheadle please confirm

**Comment by timcheadle** [comment]
Looks good! Perfect timing.
