### ISSUE TITLE
EU Central Bank undefined method `/' for nil:NilClass when I exchange_to

### ISSUE THREAD

**Issue by Zensavona** [RubyMoney/money-rails#295]
I'm having this issue with the EU Central Bank

````
rb(main):013:0> @t.amount
=> #<Money fractional:42000 currency:AUD>
irb(main):015:0* @t.amount.exchange_to(:AUD)
=> #<Money fractional:42000 currency:AUD>
irb(main):016:0> @t.amount.exchange_to(:THB)
NoMethodError: undefined method `/' for nil:NilClass
	from /Library/Ruby/Gems/2.0.0/gems/eu_central_bank-0.5.0/lib/eu_central_bank.rb:57:in `exchange_with'
	from /Library/Ruby/Gems/2.0.0/gems/money-6.5.1/lib/money/money.rb:412:in `exchange_to'
	from (irb):16
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/console.rb:110:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/console.rb:9:in `start'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Library/Ruby/Gems/2.0.0/gems/railties-4.2.0/lib/rails/commands.rb:17:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
	from /Users/zensavona/softwaredev/projects/z/money/bin/rails:8:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `block in load'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Library/Ruby/Gems/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:268:in `load'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/commands/rails.rb:6:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/command_wrapper.rb:38:in `call'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application.rb:183:in `block in serve'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application.rb:156:in `fork'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application.rb:156:in `serve'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application.rb:131:in `block in run'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `loop'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application.rb:125:in `run'
	from /Library/Ruby/Gems/2.0.0/gems/spring-1.2.0/lib/spring/application/boot.rb:18:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from -e:1:in `<main>'irb(main):017:0>
irb(main):018:0*
````

**Comment by semmons99** [comment]
could you file this with the eu gem? My guess is a currency was removed (or changes) from the service being used.
