### ISSUE TITLE
Compatibility with Mongoid 4?

### ISSUE THREAD

**Issue by ogminor** [RubyMoney/money-rails#303]
I'm having issues using this with Mongoid 4, is it still compatible?

**Comment by semmons99** [comment]
Should be. Can you give us more info?



- shane

**Comment by claudiotrindade** [comment]
With the ruby 2.2.0, rails 4.2.0 and mongoid 4.0.2, i'm having the following error:
```
/usr/local/rvm/gems/ruby-2.2.0@law/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:109:in `connection_pool': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
	from /usr/local/rvm/gems/ruby-2.2.0@law/gems/activerecord-4.2.0/lib/active_record/connection_handling.rb:105:in `connection_config'
	from /usr/local/rvm/gems/ruby-2.2.0@law/gems/money-rails-1.4.1/lib/money-rails/hooks.rb:20:in `block in init'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /usr/local/rvm/gems/ruby-2.2.0@global/gems/activesupport-4.2.0/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /usr/local/rvm/gems/ruby-2.2.0@law/gems/money-rails-1.4.1/lib/money-rails/hooks.rb:7:in `init'
	from /usr/local/rvm/gems/ruby-2.2.0@law/gems/money-rails-1.4.1/lib/money-rails/railtie.rb:4:in `block in <class:Railtie>'
	from /usr/local/rvm/gems/ruby-2.2.0@law/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
	from /usr/local/rvm/gems/ruby-2.2.0@law/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
	from /usr/local/rvm/gems/ruby-2.2.0@law/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
```

This error occurs only when using the gem 'money-rails'. If used only gems 'money' and 'monetize', the error does not occur.

The gem 'money-rails' is compatible with mongoid 4?

**Comment by antstorm** [comment]
@claudiotrindade it seems like you're using ActiveRecord with Mongoid, which is not a good idea unless you want to use both DBs at the same time. I would suggest following this guide (http://mongoid.org/en/mongoid/docs/installation.html), especially the "Getting Rid of Active Record" part.

**Comment by semmons99** [comment]
Closed due to inactivity.
