### ISSUE TITLE
exchange_to + to_json = Stackoverflow

### ISSUE THREAD

**Issue by SDEagle** [RubyMoney/money-rails#373]
In a rails 4 application (ruby 2.2.2 OS X) with money-rails master and money 6.6.1 (merged that PR in a fork) when you exchange into another currency and then call `to_json` on the money object you get `SystemStackError: stack level too deep` in ActiveSupport.

```ruby
Money.new(1_00, 'EUR').to_json # => fine
Money.new(1_00, 'EUR').exchange_to('USD') # => fine
Money.new(1_00, 'EUR').exchange_to('USD').to_json # => Stackoverflow
# even worse now suddenly
Money.new(1_00, 'EUR').to_json # => Stackoverflow
```

So far I did not try out if this happens too on a currently published gem version with money 6.5. We use this setup because we use a custom exchange rate store with the interface from money 6.6. Could be another source for the issue.

The actual stacktrace is sadly not really that interesting
```
Exception: SystemStackError: stack level too deep
--
   0: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/numeric/conversions.rb:125:in `block (2 levels) in <class:Numeric>'
   1: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/range/conversions.rb:13:in `to_s'
   2: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/range/conversions.rb:13:in `to_formatted_s'
   3: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:134:in `as_json'

      ...

7838: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
7839: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `each'
7840: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `map'
7841: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `as_json'
7842: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:50:in `as_json'
7843: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
7844: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `each'
7845: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `map'
7846: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `as_json'
7847: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:50:in `as_json'
7848: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `block in as_json'
7849: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `each'
7850: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `map'
7851: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:159:in `as_json'
7852: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:50:in `as_json'
7853: <rubypath>/gems/activesupport-4.2.4/lib/active_support/json/encoding.rb:35:in `encode'
7854: <rubypath>/gems/activesupport-4.2.4/lib/active_support/json/encoding.rb:22:in `encode'
7855: <rubypath>/gems/activesupport-4.2.4/lib/active_support/core_ext/object/json.rb:37:in `to_json_with_active_support_encoder'
```

**Comment by semmons99** [comment]
Please submit a PR with a minimal failing test.

**Comment by SDEagle** [comment]
just opened a PR with a failing spec.

Difficult thing about this bug is, that it is most likely a weird interplay between Money and Rails/ActiveSupport, so this might be the wrong place to report and fix it but on the other hand Money on it's own does not at all depend on rails and shouldn't really be concerned with this.

**Comment by tommyalvarez** [comment]
@SDEagle this is still open and being 2018 i now have this issue also, exactly the same! With rails 5.2. Did you ever figure it out ?

**Comment by antstorm** [comment]
@tommyalvarez anything particular about your setup? Can you paste a stack trace? Any change to dig deeper yourself for any clues?

**Comment by SDEagle** [comment]
Wow, that was ages ago Sadly, I have no idea anymore. We somehow got around it but I don't remember what we did there.

**Comment by tommyalvarez** [comment]
@antstorm noting really, pretty standard setup i think. Here goes the backtrace:

```
#<SystemStackError: stack level too deep>
(byebug) e.backtrace
["/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activerecord-5.2.1/lib/active_record/dynamic_matchers.rb:33:in `find'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activerecord-5.2.1/lib/active_record/dynamic_matchers.rb:33:in `match'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activerecord-5.2.1/lib/active_record/dynamic_matchers.rb:10:in `respond_to_missing?'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:53:in `respond_to?'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:53:in `as_json'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `block in as_json'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `each'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `map'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `as_json'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:56:in `as_json'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `block in as_json'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `each'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `map'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `as_json'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:56:in `as_json'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `block in as_json'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `each'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `map'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `as_json'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:56:in `as_json'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `block in as_json'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `each'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `map'", "/home/tommy/.rvm/gems/ruby-2.5.1@igalcosts/gems/activesupport-5.2.1/lib/active_support/core_ext/object/json.rb:171:in `as_json'"
```

And here is the model using money-rails:

# frozen_string_literal: true
# == Schema Information
#
# Table name: products
#
#  id                      :bigint(8)        not null, primary key
#  code                    :string           not null
#  presentation            :string           not null
#  name                    :string           not null
#  description             :string
#  cost_cents              :integer          default(0), not null
#  cost_currency           :string           default("ARS"), not null
#  weight                  :float
#  expenses                :float
#  product_type_id         :bigint(8)
#  created_at              :datetime         not null
#  updated_at              :datetime         not null
#  consumables_count       :integer          default(0), not null
#  production_rates_count  :integer          default(0), not null
#  products_services_count :integer          default(0), not null
#  packagings_count        :integer          default(0), not null
#

```
class Product < ApplicationRecord
  #
  # Gem Includes
  #
  include Selectable
  include PgSearch

  monetize :cost_cents, with_model_currency: :cost_currency, numericality: false

  #
  # Validations
  #
  validates :code, presence: true, uniqueness: {scope: :presentation}, length: {is: 8}
  validates :cost, numericality: {greater_than_or_equal_to: 0}
  validates :description, length: {in: 1..255, allow_blank: true}
  validates :expenses, presence: true, numericality: {greater_than_or_equal_to: 0}
  validates :name, presence: true, length: {in: 1..255}
  # The product must have a packaging defined if it has sterilization
  validates :packagings, presence: true, if: :sterilization_service_present?
  validates :presentation, presence: true, length: {is: 4}
  validates :product_type, presence: true
  validates :weight, presence: true, numericality: {greater_than: 0}

  #
  # Relations
  #
  belongs_to :product_type
  belongs_to :supplier, optional: true

  has_one :sterilization_service, dependent: :destroy

  has_many :consumables, dependent: :destroy, inverse_of: :product
  has_many :packagings, dependent: :destroy
  has_many :production_rates, dependent: :destroy
  has_many :procedures, through: :production_rates
  has_many :products_services, dependent: :destroy
  has_many :services, through: :products_services

  #
  # Scopes
  #
  pg_search_scope :search_for,
                  against: {
                    name: "C", code: "A", presentation: "B"
                  },
                  using: {tsearch: {any_word: false, prefix: true}, trigram: {threshold: 0.3}}, ignoring: :accents

  #
  # Delegators
  #
  delegate :unit_of_measure, to: :product_type

  #
  # Instance Methods
  #

  def cost_with_expenses
    cost + cost * (expenses / 100.0)
  end

  def cost_with_expenses_in_ars
    cost_with_expenses.exchange_to("ARS")
  end

  private

  def sterilization_service_present?
    sterilization_service.present?
  end
end
```

Finally the schema of the model:

```
create_table "products", force: :cascade do |t|
    t.string "code", null: false
    t.string "presentation", null: false
    t.string "name", null: false
    t.string "description"
    t.integer "cost_cents", default: 0, null: false
    t.string "cost_currency", default: "ARS", null: false
    t.float "weight"
    t.float "expenses"
    t.bigint "product_type_id"
    t.datetime "created_at", null: false
    t.datetime "updated_at", null: false
    t.integer "consumables_count", default: 0, null: false
    t.integer "production_rates_count", default: 0, null: false
    t.integer "products_services_count", default: 0, null: false
    t.integer "packagings_count", default: 0, null: false
    t.bigint "supplier_id"
    t.index ["code", "presentation"], name: "index_products_on_code_and_presentation", unique: true
    t.index ["code"], name: "index_products_on_code"
    t.index ["product_type_id"], name: "index_products_on_product_type_id"
    t.index ["supplier_id"], name: "index_products_on_supplier_id"
  end
```
Things to notice: I use [fast_jsonapi](https://github.com/Netflix/fast_jsonapi) serializer. The error is triggered from this line in my ProductsController#index method:

```
@products = current_search.new(search_attributes)
      .results
      .order(sort(params[:sort] || {"0": {id: "name", desc: false}}))
      .page(1).per(records_per_page)

    render json: **ProductSerializer.new(
      @products,
      include: %i[product_type supplier],
      meta: pagination_dict(@products)
    ).serialized_json**
```
The #serialized_json method, which internally uses as_json is what fails. I solved it by doing a monkey patch like this:

```
class Money
  def as_json(_options)
    {fractional: to_f, currency: {iso_code: currency.iso_code}}
  end
end

```
There must be something going on with the original implementation of to_json or as_json.

**Comment by antstorm** [comment]
#568

**Comment by hiattp** [comment]
Looking forward to https://github.com/RubyMoney/money-rails/pull/568, we have the exact same setup and issue as @tommyalvarez (Rails 5.2.3, Money 6.13.1, Money-Rails 1.13.0, Fast JSON API 1.5). Interestingly, monkey patching an `as_json` method seems to mitigate but not completely sidestep the issue. Haven't dug much further yet than to notice that

**Comment by antstorm** [comment]
@hiattp the PR's merged now. I wonder if that will work with Fast JSON API, need to have a closer look at it

**Comment by hiattp** [comment]
Thanks @antstorm, will check it out with the next money-rails release 👍

**Comment by hiattp** [comment]
Just introduced your change in a simple monkey patch to test it out—unfortunately fast json api overwrites the `to_json` implementation (afaict) so overwriting `to_hash`, `to_json` or `as_json` doesn't have an effect. The best way around this issue for fast json api seems to be specifically overriding each money attribute so that the serializer never sees a raw money object.

**Comment by antstorm** [comment]
@hiattp digging through the Fast JSON API a little bit, it seems that it will always just use whatever is returned by the attribute (https://github.com/Netflix/fast_jsonapi/blob/5ff3fa97dae4b6be51bf8ec315cb427667c4ce96/lib/fast_jsonapi/attribute.rb) and pass it straight to the encoder (it does not encode objects itself). I also didn't find any good opportunities to extend it.

One potential workaround I see is pretending that your monetized attribute is a relationship (like `has_one`), because it can be serialized using it's own serializer (for example `MoneySerializer`).

**Comment by hiattp** [comment]
Cool thanks for the idea and the deeper dive! Sounds like we have a consensus that Fast JSON API needs a bit of special handling to avoid this issue when using an exchange, there isn't much money-rails can do to mitigate it 👍

**Comment by antstorm** [comment]
@hiattp unfortunately that is what it looks like. However if you find a way — please let me know 👍

**Comment by antstorm** [comment]
@hiattp one other finding — it seems that some encoders will allow this behaviour. For example, Oj has this option — https://github.com/ohler55/oj/blob/master/pages/Options.md#use_to_hash-boolean.
