### ISSUE TITLE
Can't write unknown attribute `amount_pennies`

### ISSUE THREAD

**Issue by ben-eb** [RubyMoney/money-rails#388]
Not sure if this is a problem with money-rails or factory_girl but I'm struggling with getting simple tests to pass. I have the currency set to GBP, here are the relevant parts of the code:

```ruby
class CreatePropertyOffers < ActiveRecord::Migration
  def change
    create_table :property_offers do |t|
      t.monetize :amount

      t.timestamps null: false
    end
  end
end
```

```ruby
class PropertyOffer < ActiveRecord::Base
  monetize :amount_pennies
  serialize :amount, MoneySerializer.new
end
```

```ruby
class MoneySerializer
  def dump (money)
    money
  end

  def load (value)
    Money.new value
  end
end
```

```ruby
FactoryGirl.define do
  factory :property_offer do |f|
    f.amount { Faker::Number.number(7) }
  end
end
```

```ruby
describe PropertyOffer do
  it 'is monetized' do
    offer = FactoryGirl.create(:property_offer)
    expect(offer).to monetize(:amount).with_currency(:gbp)
  end
  # ...
end
```

My specs fail with:

```
  1) PropertyOffer is monetized
     Failure/Error: offer = FactoryGirl.create(:property_offer)
     ActiveModel::MissingAttributeError:
       can't write unknown attribute `amount_pennies`
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/attribute.rb:138:in `with_value_from_database'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/attribute_set.rb:39:in `write_from_user'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/attribute_methods/write.rb:74:in `write_attribute_with_type_cast'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/attribute_methods/write.rb:56:in `write_attribute'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/activerecord-4.2.4/lib/active_record/attribute_methods/dirty.rb:96:in `write_attribute'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/money-rails-1.4.1/lib/money-rails/active_record/monetizable.rb:170:in `block (2 levels) in monetize'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:16:in `public_send'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:16:in `block (2 levels) in object'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `each'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:15:in `block in object'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `tap'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/attribute_assigner.rb:14:in `object'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/evaluation.rb:12:in `object'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy/create.rb:9:in `result'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory.rb:42:in `run'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:23:in `block in run'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/activesupport-4.2.4/lib/active_support/notifications.rb:166:in `instrument'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/factory_runner.rb:22:in `run'
     # /Users/beneb/.rvm/gems/ruby-2.2.1/gems/factory_girl-4.5.0/lib/factory_girl/strategy_syntax_method_registrar.rb:20:in `block in define_singular_strategy_method'
     # ./spec/models/property_offer_spec.rb:9:in `block (2 levels) in <top (required)>'
```

Any advice would be appreciated! Thanks.

**Comment by ben-eb** [comment]
Managed to fix this by using the info from http://stackoverflow.com/questions/30010565/money-rails-gem-and-instance-currencies/30106138#30106138.

```ruby
class PropertyOffer < ActiveRecord::Base
  monetize :amount_pennies, with_model_currency: :amount_currency
end
```

**Comment by semmons99** [comment]
Thanks for posting the follow-up! 



- shane
