### ISSUE TITLE
Rspec cannot run after gem install money-rails

### ISSUE THREAD

**Issue by TravisTam** [RubyMoney/money-rails#414]
any ideas

```
/Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:109:in `connection_pool': ActiveRecord::ConnectionNotEstablished (ActiveRecord::ConnectionNotEstablished)
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activerecord-4.2.5/lib/active_record/connection_handling.rb:105:in `connection_config'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/money-rails-1.4.1/lib/money-rails/hooks.rb:20:in `block in init'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:38:in `instance_eval'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:38:in `execute_hook'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:28:in `block in on_load'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:27:in `each'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/lazy_load_hooks.rb:27:in `on_load'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/money-rails-1.4.1/lib/money-rails/hooks.rb:7:in `init'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/money-rails-1.4.1/lib/money-rails/railtie.rb:4:in `block in <class:Railtie>'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:30:in `run'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:226:in `block in sort_each'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `call'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:224:in `sort_each'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/2.2.0/tsort.rb:203:in `sort_each'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/railties-4.2.5/lib/rails/application.rb:352:in `initialise!'
	from /Users/Sunny/Documents/Project/Swiggers/swiggers-api/config/environment.rb:5:in `<top (required)>'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/Sunny/Documents/Project/Swiggers/swiggers-api/spec/rails_helper.rb:2:in `<top (required)>'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:274:in `require'
	from /Users/Sunny/Documents/Project/Swiggers/swiggers-api/spec/controllers/v1/bookmark_posts_controller_spec.rb:1:in `<top (required)>'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/dependencies.rb:268:in `load'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1361:in `block in load_spec_files'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1359:in `each'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/configuration.rb:1359:in `load_spec_files'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:106:in `setup'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:92:in `run'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:78:in `run'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.2/lib/rspec/core/runner.rb:45:in `invoke'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/rspec-core-3.4.2/exe/rspec:4:in `<top (required)>'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/bin/rspec:23:in `load'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/bin/rspec:23:in `<main>'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/bin/ruby_executable_hooks:15:in `eval'
	from /Users/Sunny/.rvm/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/bin/ruby_executable_hooks:15:in `<main>
```

**Comment by TravisTam** [comment]
I have found the problem, this is caused by the below code.

https://github.com/RubyMoney/money-rails/blob/master/lib/money-rails/hooks.rb#L20

I have commented L20,L21 and L27-29, rspec run perfectly. Is it possible to review coding on these line for rspec support?

**Comment by marlonmantilla** [comment]
Hi guys, getting the same here when trying to install money-rails 1.6.0 and rails 4.2.1, had to downgrade to `gem 'money-rails', '1.2.0'` in order to have running tests passed, otherwise it will return the same error. 

Rspec versions: 

` rspec-core (3.3.2)
rspec-expectations (3.3.1)
rspec-mocks (3.3.2)
rspec-rails (3.3.3)
rspec-support (3.3.0)
`

**Comment by antstorm** [comment]
@marlonmantilla which database adapter are you using for your tests? Is it different from other environments?

**Comment by marlonmantilla** [comment]
@antstorm currently using Postgres and it's the same for all environments. Using `pg (0.18.3)`

**Comment by antstorm** [comment]
Got it, I will take a closer look at it

**Comment by marlonmantilla** [comment]
Awesome, thanks @antstorm if helps this is my current working Gemfile, just switch it to 1.6.0 and you will get the error hopefully...

```ruby
    source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'pg'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'sass-rails', '~> 4.0.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'
gem 'active_model_serializers'
gem "devise"
gem 'carrierwave'
gem 'cloudinary'
gem 'rails_12factor', group: :production
gem 'rack-cors', :require => 'rack/cors'
gem 'acts-as-taggable-on', '~> 3.4'
gem 'rollbar', '~> 1.2.7'
gem 'dotenv-rails', :groups => [:development, :test]
gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby'
gem 'authority'
gem 'money-rails', '1.2.0'

group :development, :test do
  gem 'byebug'
  gem 'spring'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'ffaker'
end

group :test do
  gem "shoulda-matchers", ">= 3.0.0",
    require: false
end


```

**Comment by antstorm** [comment]
@marlonmantilla ok, so I did some testing and couldn't get that error. I even created a new rails project with a bare minimum setup including `pg`, `money-rails` and `rspec-rails` and got no error.

Can you please share your `database.yml` (don't forget to remove any sensible info first)?
